[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "steinernet"
version = "0.1.8"  # bump each release
description = "A SteinerTree library implementing several huristic and exact steiner methods."
readme = "README.md"
requires-python = ">=3.6"
license = "Apache-2.0"
authors = [{ name = "Afshin Sadeghi", email = "sadeghi.afshin@gmail.com" }]
dependencies = [
  "networkx>=2.0"
]

[project.scripts]
steinernet = "steiner.SteinerNet:main"

[tool.setuptools]
packages = ["steinernet"]
include-package-data = true
